"""SQLAlchemy ORM model for system alerts and anomaly notifications.

Alerts are created by AI modules (water quality, growth, feeding) or
manually by operators. Severity levels follow standard NOC conventions.

TODO (Phase 3): Add notification_sent flag and delivery channel tracking.
"""

from datetime import datetime

from sqlalchemy import Boolean, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


class Alert(Base):
    """System alert generated by AI modules or operators."""

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    tank_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(nullable=False, index=True)
    resolved_at: Mapped[datetime | None] = mapped_column(nullable=True)

    # Alert classification
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="'critical' | 'warning' | 'info'",
    )
    category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="'water_quality' | 'fish_growth' | 'feeding' | 'equipment'",
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)

    # Context from the triggering module
    metric_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    metric_value: Mapped[str | None] = mapped_column(String(50), nullable=True)
    threshold_value: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, index=True)
    resolution_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    resolved_by: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Source: 'water_quality_ai' | 'growth_ai' | 'feeding_ai' | 'manual' | 'agent'
    source: Mapped[str] = mapped_column(String(50), default="system")

    __table_args__ = (
        Index("ix_alert_tank_active", "tank_id", "is_active"),
        Index("ix_alert_time", "created_at"),
    )
