"""Alerts API — anomaly detection notifications and alert management.

Alerts are generated by the water quality virtual sensor, AI modules,
and the optimization agent when thresholds are exceeded.

TODO (Phase 3): Add alert suppression rules and escalation policies.
"""


import redis.asyncio as aioredis
from fastapi import APIRouter, Depends, Query, Request
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.limiter import LIMIT_ALERT_WRITE, is_internal_service, limiter
from app.db.redis import get_redis
from app.db.session import get_db
from app.schemas.alert import AlertCreate, AlertRead, AlertUpdate
from app.services.monitoring_service import MonitoringService

router = APIRouter()


@router.get("/", response_model=list[AlertRead], summary="List alerts")
async def list_alerts(
    tank_id: str | None = Query(None, description="Filter by tank"),
    active_only: bool = Query(True, description="Return only unresolved alerts"),
    limit: int = Query(50, ge=1, le=200),
    db: AsyncSession = Depends(get_db),
) -> list[AlertRead]:
    """Return a list of alerts, optionally filtered by tank or status.

    Args:
        tank_id: Optional tank filter.
        active_only: If True, return only unresolved (active) alerts.
        limit: Maximum records.
        db: Injected async DB session.

    Returns:
        List of AlertRead records.
    """
    service = MonitoringService(db)
    return await service.list_alerts(
        tank_id=tank_id, active_only=active_only, limit=limit
    )


@router.post("/", response_model=AlertRead, status_code=201, summary="Create alert")
@limiter.limit(LIMIT_ALERT_WRITE, exempt_when=is_internal_service)
async def create_alert(
    request: Request,
    payload: AlertCreate,
    db: AsyncSession = Depends(get_db),
    redis: aioredis.Redis = Depends(get_redis),
) -> AlertRead:
    """Create a new alert record and push to real-time subscribers.

    Published to Redis channel ``events:alerts`` so WebSocket clients
    receive the alert immediately without polling.

    Args:
        payload: Alert creation payload.
        db: Injected async DB session.
        redis: Injected Redis client.

    Returns:
        Created AlertRead record.

    TODO (Phase 3): Restrict this endpoint to internal service-to-service calls.
    """
    service = MonitoringService(db, redis=redis)
    return await service.create_alert(payload)


@router.patch("/{alert_id}/resolve", response_model=AlertRead, summary="Resolve alert")
async def resolve_alert(
    alert_id: int,
    payload: AlertUpdate,
    db: AsyncSession = Depends(get_db),
) -> AlertRead:
    """Mark an alert as resolved.

    Args:
        alert_id: Alert primary key.
        payload: Resolution notes.
        db: Injected async DB session.

    Returns:
        Updated AlertRead record.
    """
    service = MonitoringService(db)
    return await service.resolve_alert(alert_id, payload)
