apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: aquafarm
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # headless for StatefulSet DNS: postgres-0.postgres.aquafarm.svc
